# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np
a = np.arange(10)
b = np.reshape(a, (2,5))
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [18]:
arrayOne = np.arange(10).reshape(2 , 5)
arrayTwo = np.arange(10 , 20).reshape(2 , 5)
np.vstack((arrayOne , arrayTwo))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [20]:
arrayOne = np.arange(10).reshape(2 , 5)
arrayTwo = np.arange(10 , 20).reshape(2 , 5)
np.hstack((arrayOne , arrayTwo))

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [23]:
arrayOne = np.arange(10).reshape(2 , 5)
print(arrayOne)
arrayA = arrayOne.flatten()
arrayA

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [27]:
arrayOne = np.arange(20).reshape(4 , 5)
arrayD = arrayOne.reshape(-1)
print(arrayOne)
arrayD

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [30]:
arrayOne = np.arange(20).reshape(4 , 5)
array = arrayOne.reshape(4 , -1)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [33]:
arrayOne = np.arange(25).reshape(5, 5)
print(arrayOne)
np.square(arrayOne)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [37]:
arrayMean = np.arange(30).reshape(5 , 6)
print(arrayMean)
np.mean(arrayMean)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [42]:
print(arrayMean)
np.std(arrayMean)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [43]:
print(arrayMean)
np.median(arrayMean)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [44]:
print(arrayMean)
np.transpose(arrayMean)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [46]:
arraydiagnal = np.arange(16).reshape(4 , 4)
print(arraydiagnal)
np.trace(arraydiagnal)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [47]:
np.linalg.det(arraydiagnal)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [58]:
array = np.arange(10)
array5th = np.percentile(array, 5)
array95th = np.percentile(array, 95)
print(array5th, array95th)

0.45 8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [67]:
array = np.ones((5,5))
array[1:-1,1:-1] = "nan"
arrayIsnull = np.isnan(array)
print(array)
arrayIsnull

[[ 1.  1.  1.  1.  1.]
 [ 1. nan nan nan  1.]
 [ 1. nan nan nan  1.]
 [ 1. nan nan nan  1.]
 [ 1.  1.  1.  1.  1.]]


array([[False, False, False, False, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False]])