# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np


2. Create a null vector of size 10 

In [2]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
vect = np.arange(10 , 50)
vect

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
vect.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
vect.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [7]:
vect.ndim

1

8. Create a boolean array with all the True values

In [8]:
boolArray = np.ones(10 , dtype=bool)
boolArray

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [9]:
arr2 = np.random.randn(3 , 3)
arr2

array([[ 1.06456731,  1.13736469, -0.20352554],
       [-0.81527741,  1.38517359, -1.42609455],
       [-0.0103846 , -1.33398109, -0.26469412]])

10. Create a three dimensional array



In [10]:
arr3 = np.random.randn(3 , 4 , 3)
arr3

array([[[ 1.0995159 , -1.75534425, -0.83897844],
        [-0.97276123, -0.78842239, -0.57125951],
        [ 0.41593097,  1.41581966,  0.02599619],
        [ 0.18579087,  0.29904323, -1.05897412]],

       [[-0.50897123,  1.50850968, -0.39430212],
        [-0.29623574,  0.14432471,  0.2978155 ],
        [-0.3898255 , -0.04800828,  1.245164  ],
        [-1.10450447,  0.17885936, -0.14630733]],

       [[-0.21864953, -1.96350329,  1.76840675],
        [-2.72710443, -0.27701957,  0.15732693],
        [ 0.55966525, -0.57690511, -0.33457376],
        [-0.37350256,  0.91241486, -1.36413473]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
#non-Reversed
nonReversedVector = np.arange(10)
print(nonReversedVector)
#----------------
#Reversed Veactor
#----------------
reversedVector = np.flip(nonReversedVector)
print(reversedVector)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
nullVector = np.zeros(10)
nullVector[4] = 1
nullVector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [16]:
identityArray = np.eye(3)
identityArray

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [19]:
arr = np.array([1, 2, 3, 4, 5])
arrFloat = arr.astype(np.float64)
arrFloat.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [20]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr3 = np.multiply(arr1, arr2)
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [21]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3 = (arr1 == arr2)
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [23]:
arr = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 ])
arr[arr%2 == 1]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [24]:
arr = np.where(arr % 2 == 1 , -1 , 0)
arr

array([-1,  0, -1,  0, -1,  0, -1,  0, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [27]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [34]:
array2d = np.ones((5,5))
array2d[1:-1,1:-1] = 0
array2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [37]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d = np.where(arr2d == 5 , 12 , arr2d)
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d = np.where(arr3d < 4 , 64 , arr3d)
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [6]:
array2dimentional = np.arange(10).reshape(2 , 5)
array1dim = array2dimentional[0]
array1dim

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [9]:
array2dim = np.arange(10).reshape(2 , 5)
array2dim2ndval = array2dim[1][1]
array2dim2ndval

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [82]:
twoDimArr = np.arange(10).reshape(2, 5)
twoDimArr[0:1 , 2:2]

array([], shape=(1, 0), dtype=int64)

26. Create a 10x10 array with random values and find the minimum and maximum values

In [17]:
tenXten = np.random.randn(10 , 10)
a = tenXten.min()
b = tenXten.max()
#a = minimum && b = maximum
print(a , b)
tenXten

-3.434730675585998 2.305734010763769


array([[-0.92698359,  0.1492441 ,  1.04376415, -0.10418687,  2.1788263 ,
         0.23224791, -0.26925001, -0.80324608,  0.69213139, -3.43473068],
       [-2.21290379, -0.2576103 , -0.74643081,  0.44488753,  0.75327492,
        -1.99212905, -0.61945963, -1.30690581,  0.46981601,  1.52668832],
       [-1.27558713,  0.06574699,  1.04771952,  1.00511971,  0.4245382 ,
        -0.51650942, -0.93619782, -0.37012506,  0.70197318, -0.31842763],
       [-0.2698748 , -0.78200519, -0.64193426, -1.38089711,  1.43541435,
         0.65613886,  0.55987651, -0.14454227,  0.20033077,  0.03757421],
       [-0.70471452, -0.05655681,  0.25898677, -0.81153291, -0.57774135,
         0.9259431 ,  2.30573401,  1.46476494,  0.85299383,  0.23744787],
       [-0.02471279, -0.10522874, -0.05834359,  1.12770004,  0.52596514,
        -0.05069404,  0.02604471,  0.02647813, -0.80019875, -0.37021102],
       [-0.74126749,  0.86688292, -0.32303665,  0.17880452, -1.36676644,
         0.19509279,  0.75660629,  1.01343993

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a , b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [41]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(np.in1d(a , b))[0]
c

array([1, 3, 5, 7])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [9]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randn(7, 4)
data[names == 'Will']

array([[-0.74057404, -1.33302828, -0.48682604,  0.43257053],
       [ 0.67188128, -0.02159062,  1.10245615, -1.92081847]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [21]:
a = data[names != 'Will']
b = data[names != 'Joe']
print (a , b)

[[-1.5183874   0.47709529 -1.42699561 -1.06299945]
 [-0.38980821 -0.28675636  1.68918645  0.7568201 ]
 [-0.3737231  -0.14061634  1.09202489  1.80606687]
 [-2.36535519 -0.17605482  0.79160674  1.56990821]
 [-3.05849915 -0.26506708  0.35737762  1.1673361 ]] [[-1.5183874   0.47709529 -1.42699561 -1.06299945]
 [-0.74057404 -1.33302828 -0.48682604  0.43257053]
 [-0.3737231  -0.14061634  1.09202489  1.80606687]
 [ 0.67188128 -0.02159062  1.10245615 -1.92081847]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [28]:
z = np.arange(1, 16).reshape(5 , 3)
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [29]:
x = np.arange(1 , 17).reshape(2, 2, 4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [33]:
c = x.swapaxes(1 , 2)
c

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [47]:
sqrt = np.random.random(10)
sqrt = np.sqrt(sqrt)
sqrt[sqrt < 0.5] = 0
sqrt

array([0.66369467, 0.        , 0.96537854, 0.96505687, 0.9214528 ,
       0.        , 0.        , 0.90066902, 0.77996102, 0.94130271])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [16]:
arrX = np.random.randint(12, size=12)
arrY = np.random.randint(12, size=12)
print(arrX , arrY)
print(np.maximum(arrX , arrY))

[ 8  9  2  1  1  1  5 10  4  5  7  8] [ 3  5  7  4  4  7  8  5  3  8  2 10]
[ 8  9  7  4  4  7  8 10  4  8  7 10]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniqueNames = np.unique(names)
uniqueNamesSort = np.sort(uniqueNames)
uniqueNamesSort

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [63]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a , b)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [62]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
newSample = np.delete(sampleArray, 1, 0)
xyz = np.insert(newSample,1,[newColumn],axis = 0) 
xyz

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [42]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x , y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [38]:
matrix = np.random.rand(20,20)
np.cumsum(matrix)



array([  0.2640332 ,   0.569909  ,   0.66444077,   0.94119024,
         1.76427677,   2.10088123,   2.40274916,   3.30864532,
         4.26543108,   4.69203062,   5.35475903,   6.19640012,
         6.64833151,   6.95569027,   7.90911697,   8.68887772,
         9.26188924,   9.81585008,  10.21172084,  10.72969982,
        10.85144608,  11.15837128,  11.72970572,  12.24322621,
        12.4866936 ,  12.98426916,  13.87811285,  14.04141554,
        14.40885914,  15.24407779,  15.69169597,  15.78276928,
        16.49959271,  17.20324256,  17.3198518 ,  17.47184781,
        17.69337377,  18.62662321,  18.97253687,  19.88001422,
        20.27830392,  20.36481368,  20.56143315,  20.90870539,
        21.72508813,  22.4796658 ,  23.35022792,  23.49732288,
        23.88882749,  24.42029011,  25.27920608,  25.93984423,
        26.75016665,  27.16348495,  27.64345015,  27.78002063,
        28.40378844,  28.69623014,  29.10171821,  29.66964425,
        30.31726145,  30.43146945,  31.16056943,  31.86